server {
    listen 8887;
    server_name _;

    # /
    location / {
        proxy_pass http://[::1]:8888/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Accept-Encoding "";
        
        sub_filter '<head>' '<head><base href="$http_x_ingress_path/"><script>(function(){try{var url=window.location.origin+window.location.pathname;localStorage.setItem("ledfx-hosts", JSON.stringify([url]));}catch(e){}})();</script>';
        sub_filter_types text/plain text/css text/javascript text/event-stream application/javascript application/json application/manifest+json;
        sub_filter_once off;
        
        sub_filter '="/'    '="$http_x_ingress_path/';
        sub_filter 'url(/'  'url($http_x_ingress_path/';
        sub_filter 'url("/' 'url("$http_x_ingress_path/';
        sub_filter "url('/" "url('$http_x_ingress_path/";
        #sub_filter '<link rel="manifest" href="' '<link crossorigin="use-credentials" rel="manifest" href="';
    }

    # /api/websocket
    location /api/websocket {
        proxy_pass http://[::1]:8888/api/websocket;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_read_timeout 3600s;
    }
}