slug: "sendspin"
name: "Sendspin"
description: "Play back music through audio interfaces, that are connected to Home Assistants host-system"
version: "0.50"
stage: "experimental"
startup: services
init: false

host_network: true
audio: true
realtime: true

arch:
  - aarch64
  - amd64

map:
  - addon_config:rw

schema:
  name: str?
  id: str?
  url: str?
  volume_controls: list(Hardware|Software|Boosted)?
  log_level: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)?