slug: "ledfx"
name: "LedFx"
description: "Animate LED's with music from Music Assistant/Sendspin & other sources."
version: "0.5"
init: false
audio: true
realtime: true
host_network: true

arch:
  - aarch64
  - amd64
map:
  - app_config:rw

startup: services